sudo: required
services:
  - docker

before_install:
  - docker build -t robzilla3000/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true robzilla3000/react-test npm test -- --watchAll=false

after_success:
  - docker build -t robzilla3000/multi-client ./client
  - docker build -t robzilla3000/multi-nginx ./nginx
  - docker build -t robzilla3000/multi-server ./server
  - docker build -t robzilla3000/multi-worked ./worker
  # Log in to the docker CLI
  - ehco "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push robzilla3000/multi-client
  - docker push robzilla3000/multi-nginx
  - docker push robzilla3000/multi-server
  - docker push robzilla3000/multi-worker